import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import { FiInstagram, FiPhone, FiMapPin, FiMail } from 'react-icons/fi';

import logoFb from '../../public/assets/logoFb.png';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Oliveira Rios Advogados',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} flex flex-row flex-wrap`}>
        <header className="h-screen w-3/12 bg-white p-10 flex flex-row flex-wrap justify-between">
          <nav className="w-full flex flex-wrap justify-center gap-6">
            <Image
              src={logoFb}
              sizes="100vw"
              style={{
                width: 'auto',
                height: 'auto',
                maxWidth: '260px',
                maxHeight: '149px',
              }}
              className="grow"
              alt="Logo OR Advogados"
            />
            <ul className="w-full">
              <li className="w-full flex justify-center mb-1 p-2 bg-primary text-white shadow-lg shadow-primary/50 hover:shadow-none hover:cursor-pointer transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-gray-main duration-300">
                <Link href={'/'}>Página Inicial</Link>
              </li>
              <li className="w-full flex justify-center p-2 bg-primary text-white shadow-lg shadow-primary/50 hover:shadow-none hover:cursor-pointer transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-gray-main duration-300">
                <Link href={'/about'}>Notícias</Link>
              </li>
              <li className="w-full flex justify-center p-2 bg-primary text-white shadow-lg shadow-primary/50 hover:shadow-none hover:cursor-pointer transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-gray-main duration-300">
                <Link href={'/about'}>Sobre</Link>
              </li>
              <li className="w-full flex justify-center p-2 bg-primary text-white shadow-lg shadow-primary/50 hover:shadow-none hover:cursor-pointer transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-gray-main duration-300">
                <Link href={'/contact'}>Pro Bono</Link>
              </li>
            </ul>
          </nav>
          <footer className="w-full border-t border-primary/25 p-4 self-end flex flex-row flex-wrap text-xs">
            <div className="w-full h-6 mb-6 flex flex-row flex-nowrap justify-center">
              <FiInstagram className="w-6 h-6" />
            </div>
            <div className="w-1/2 mb-2">
              <b>Telefone:</b>
              <p className="flex flex-row flex-nowrap">
                <p>
                  <FiPhone />
                </p>
                &nbsp;(61) 2107-9419
              </p>
            </div>
            <div className="w-1/2 mb-2">
              <b>Email:</b>
              <p className="flex flex-row flex-nowrap">
                <p>
                  <FiMail />
                </p>
                &nbsp;atendimento@oliveirarios.adv.br
              </p>
            </div>
            <div className="w-full">
              <b>Endereço:</b>{' '}
              <a
                href="https://goo.gl/maps/1Zm88MR5VpABwLVe6"
                target="_blank"
                rel="noreferrer"
                className="flex flex-row flex-nowrap"
              >
                <p>
                  <FiMapPin />
                </p>
                &nbsp; SHS Quadra 6, conjunto A, bloco A, sala 501, Complexo
                Brasil 21, Asa Sul, Brasília - DF
              </a>
            </div>
            <p className="w-full mt-6 flex justify-center">
              Copyright &copy; 2023 | Oliveira Rios Advogados
            </p>
          </footer>
        </header>
        <main className="w-9/12 p-24 bg-gradient-to-r from-primary to-secondary">
          {children}
        </main>
      </body>
    </html>
  );
}
